"""Example 10: MCP Server -- creating and testing a custom MCP server.

Demonstrates:
- Creating an MCPServer with the tool decorator
- Saving the server as a temporary file
- Running the server as a subprocess
- Lifecycle: connect, discover, call, disconnect
- Dual mode: automatic (full lifecycle) and interactive (call tools manually)

Run:
    python examples/09_mcp_server.py                  # automatic mode
    python examples/09_mcp_server.py -m interactive   # interactive mode
"""

from __future__ import annotations

import os
import sys
import tempfile

import click
from rich.panel import Panel
from rich.prompt import Prompt
from rich.syntax import Syntax
from rich.table import Table

from conftest import (
    console,
    ensure_path,
    load_env,
    setup_example,
    dual_mode_options,
    run_async,
)

ensure_path()
load_env()

from pathlib import Path

GREETING_SERVER_CODE = '''\
"""Greeting MCP Server -- generated by 09_mcp_server.py example."""
import sys
sys.path.insert(0, ".")

from koboi.mcp.server import MCPServer

server = MCPServer(name="greeting-server", version="1.0.0")


@server.tool(
    name="greet",
    description="Generate a greeting message",
    input_schema={
        "type": "object",
        "properties": {
            "name": {"type": "string", "description": "Name to greet"},
            "style": {
                "type": "string",
                "enum": ["formal", "casual"],
                "description": "Greeting style",
            },
        },
        "required": ["name"],
    },
)
def greet(name: str, style: str = "casual") -> str:
    if style == "formal":
        return f"Welcome, Mr./Ms. {name}. Nice to meet you."
    return f"Hello {name}! How are you?"


@server.tool(
    name="farewell",
    description="Generate a farewell message",
    input_schema={
        "type": "object",
        "properties": {
            "name": {"type": "string", "description": "Name"},
        },
        "required": ["name"],
    },
)
def farewell(name: str) -> str:
    return f"Goodbye, {name}! Have a great day."


if __name__ == "__main__":
    server.run()
'''


def _write_server_file():
    """Write greeting server to a temporary file."""
    tmp_dir = tempfile.mkdtemp(prefix="koboi_mcp_")
    server_file = Path(tmp_dir) / "greeting_server.py"
    server_file.write_text(GREETING_SERVER_CODE, encoding="utf-8")
    return tmp_dir, server_file


def run_automatic():
    """Full lifecycle test automatically."""
    console.print("\n[bold cyan]Step 1: Greeting MCP Server Code[/bold cyan]")
    syntax = Syntax(GREETING_SERVER_CODE, "python", theme="monokai", line_numbers=True)
    console.print(syntax)

    console.print("\n[bold cyan]Step 2: Writing server to temporary file[/bold cyan]")
    tmp_dir, server_file = _write_server_file()
    console.print(f"  File: {server_file}")

    console.print("\n[bold cyan]Step 3: Lifecycle Test (connect -> discover -> call -> disconnect)[/bold cyan]")

    from koboi.mcp.client import MCPClient

    server_cmd = [sys.executable, str(server_file)]
    console.print(f"  Command: {' '.join(server_cmd)}")

    mcp_client = MCPClient(server_command=server_cmd)

    try:
        # Connect
        console.print("\n  [bold]3a. Connect[/bold]")
        server_info = mcp_client.connect()
        console.print("  [green]Connected![/green]")
        info_table = Table(show_header=False, box=None)
        info_table.add_column("Key", style="cyan")
        info_table.add_column("Value", style="white")
        si = server_info.get("serverInfo", {})
        info_table.add_row("Server Name", si.get("name", "?"))
        info_table.add_row("Version", si.get("version", "?"))
        info_table.add_row("Protocol", server_info.get("protocolVersion", "?"))
        console.print(info_table)

        # Discover
        console.print("\n  [bold]3b. Discover Tools[/bold]")
        tools = mcp_client.discover_tools()
        console.print(f"  [green]Discovered {len(tools)} tool(s)[/green]")

        disc_table = Table(title="Discovered Tools")
        disc_table.add_column("#", justify="right", style="dim")
        disc_table.add_column("Name", style="cyan")
        disc_table.add_column("Description", style="white")
        disc_table.add_column("Required Params", style="yellow")

        for idx, t in enumerate(tools, 1):
            required = t.input_schema.get("required", [])
            disc_table.add_row(str(idx), t.name, t.description, ", ".join(required))

        console.print(disc_table)

        # Call tools
        console.print("\n  [bold]3c. Call: greet[/bold]")
        call_table = Table(title="Tool Call Results")
        call_table.add_column("Tool", style="cyan")
        call_table.add_column("Arguments", style="yellow")
        call_table.add_column("Result", style="green")

        result1 = run_async(mcp_client.call_tool("greet", {"name": "Andi", "style": "casual"}))
        call_table.add_row("greet", '{"name": "Andi", "style": "casual"}', result1)

        result2 = run_async(mcp_client.call_tool("greet", {"name": "Budi Santoso", "style": "formal"}))
        call_table.add_row("greet", '{"name": "Budi Santoso", "style": "formal"}', result2)

        result3 = run_async(mcp_client.call_tool("farewell", {"name": "Siti"}))
        call_table.add_row("farewell", '{"name": "Siti"}', result3)

        console.print(call_table)

        # Close
        console.print("\n  [bold]3d. Disconnect[/bold]")
        mcp_client.close()
        console.print("  [green]Disconnected. Server subprocess terminated.[/green]")

    except Exception as e:
        console.print(f"\n  [red]Error: {e}[/red]")
        mcp_client.close()
        raise
    finally:
        try:
            server_file.unlink(missing_ok=True)
            os.rmdir(tmp_dir)
        except OSError:
            pass

    console.print()
    console.print(
        Panel(
            "MCP server lifecycle completed successfully:\n"
            "  1. Server code written to temporary file\n"
            "  2. Client connect + initialize handshake\n"
            "  3. 2 tools discovered: greet, farewell\n"
            "  4. 3 tool calls succeeded (greet x2, farewell x1)\n"
            "  5. Client disconnect + cleanup",
            title="Summary",
            border_style="green",
        )
    )


def run_interactive():
    """Interactive tool calling on the MCP server."""
    tmp_dir, server_file = _write_server_file()
    console.print(f"[dim]Server file: {server_file}[/dim]\n")

    from koboi.mcp.client import MCPClient

    server_cmd = [sys.executable, str(server_file)]
    mcp_client = MCPClient(server_command=server_cmd)

    try:
        server_info = mcp_client.connect()
        tools = mcp_client.discover_tools()

        console.print(f"[green]Connected![/green] Server: {server_info.get('serverInfo', {}).get('name', '?')}")
        console.print(f"[dim]Available tools: {', '.join(t.name for t in tools)}[/dim]\n")
        console.print("[dim]Commands: 'greet <name> [casual|formal]', 'farewell <name>', 'quit'[/dim]\n")

        while True:
            try:
                user_input = Prompt.ask("[bold green]Command[/bold green]")
            except (KeyboardInterrupt, EOFError):
                console.print("\n[dim]Bye![/dim]")
                break

            stripped = user_input.strip().lower()
            if stripped in ("quit", "exit", "q"):
                console.print("[dim]Bye![/dim]")
                break
            if not user_input.strip():
                continue

            parts = user_input.strip().split()
            cmd = parts[0].lower()

            try:
                if cmd == "greet" and len(parts) >= 2:
                    name = " ".join(parts[1:]) if parts[-1] not in ("casual", "formal") else " ".join(parts[1:-1])
                    style = parts[-1] if parts[-1] in ("casual", "formal") else "casual"
                    result = run_async(mcp_client.call_tool("greet", {"name": name, "style": style}))
                    console.print(f"  [green]Result:[/green] {result}")
                elif cmd == "farewell" and len(parts) >= 2:
                    name = " ".join(parts[1:])
                    result = run_async(mcp_client.call_tool("farewell", {"name": name}))
                    console.print(f"  [green]Result:[/green] {result}")
                else:
                    console.print("[yellow]Usage: greet <name> [casual|formal] | farewell <name>[/yellow]")
            except Exception as e:
                console.print(f"[red]Error: {e}[/red]")

    except Exception as e:
        console.print(f"[red]Connection failed: {e}[/red]")
    finally:
        mcp_client.close()
        try:
            server_file.unlink(missing_ok=True)
            os.rmdir(tmp_dir)
        except OSError:
            pass


@click.command()
@dual_mode_options
def main(mode: str, verbose: bool):
    """Example 10: MCP Server."""
    setup_example(
        "Example 10: MCP Server",
        "Creating a custom MCP server with the tool decorator,\n"
        "running it as a subprocess, and testing the lifecycle.\n\n"
        "[dim]Run with -m interactive to call tools manually.[/dim]",
    )

    if mode == "interactive":
        run_interactive()
    else:
        run_automatic()


if __name__ == "__main__":
    main()
